### ISSUE TITLE
Błąd przy większej ilości produktów w poszczególnych kategoriach

### ISSUE THREAD

**Issue by Lotzer** [caspros/BazyDanychSklepik#108]
Błąd przy większej ilości produktów w poszczególnych kategoriach. Pozycje wychodzą poza stronę przez stópkę za miast tworzyć kolejne strony po 5 produktów. Tyczy się wszystkich kategorii Poza kategorią "wszystko".

**Comment by caspros** [comment]
Naprawione :)
