### ISSUE TITLE
Błędnie wyświetlane produkty na aplikacji mobilnej

### ISSUE THREAD

**Issue by caspros** [caspros/BazyDanychSklepik#119]
Np. mikrofalówka Samsung (kategoria AGD) wyświetla się źle, rozjeżdża się w prawo.
![blad1](https://user-images.githubusercontent.com/56698760/72430568-03b2ef80-3793-11ea-8a56-f147a60c289a.png)

**Comment by Lotzer** [comment]
Naprawione! Poprawnie wyświetlane są już produkty i pionowo i poziomo.

**Comment by ghost** [comment]
![obraz](https://user-images.githubusercontent.com/56649353/72463397-704dde80-37d3-11ea-9f18-7c35ca34d2b2.png)

**Comment by caspros** [comment]
Super, zamykam.
