### ISSUE TITLE
Błędne wyświetlanie textarea w oceń produkt na mobilnej

### ISSUE THREAD

**Issue by caspros** [caspros/BazyDanychSklepik#120]
W oceń sklep pewnie to samo jest.
![image](https://user-images.githubusercontent.com/56698760/72432775-2562a580-3798-11ea-929b-6702c454cd73.png)

**Comment by Lotzer** [comment]
Naprawione! Wkrótce trafi tu screen potwierdzający efekt.

**Comment by ghost** [comment]
![obraz](https://user-images.githubusercontent.com/56649353/72474020-4226c980-37e8-11ea-97fc-b39cd3a44dc1.png)

**Comment by caspros** [comment]
Super, zamykam.
