### ISSUE TITLE
Błąd wyświetlania w wersji mobilnej Oceń zakupione produkty

### ISSUE THREAD

**Issue by Lotzer** [caspros/BazyDanychSklepik#121]
Przycisk wyjeżdża poza krawędź ekranu przy mniejszej rozdzielczości. Issues ku pamięci!

**Comment by ghost** [comment]
![obraz](https://user-images.githubusercontent.com/56649353/72463701-24e80000-37d4-11ea-8df1-76d6fa2f5df5.png)

**Comment by Lotzer** [comment]
Kolejny naprawiony błąd!

**Comment by ghost** [comment]
![obraz](https://user-images.githubusercontent.com/56649353/72473714-954c4c80-37e7-11ea-91b0-5688095524ea.png)

**Comment by caspros** [comment]
Super, zamykam.
